In [1]:
import sys
sys.path.append("..")
import utility.utility_functions as ut
import pandas as pd

In [2]:
df = ut.load_post_data_prep_all_zone()

In [3]:
df.dropna(inplace=True)
df = df.drop(df[df.trip_time < 5].index)
df = df.drop('pickup_date',axis=1)
df.reset_index(inplace=True,drop=True)

In [8]:
main_df = ut.get_dummies(['weekday','time_binned'],df)
main_df = ut.swap_first_and_last_col(main_df)
main_df

,Zone,00:00 - 00:59,01:00 - 01:59,02:00 - 02:59,03:00 - 03:59,04:00 - 04:59,05:00 - 05:59,06:00 - 06:59,07:00 - 07:59,08:00 - 08:59,...,Tdep,HDD,CDD,Precipitation,new_snow,snow_depth,trip_distance,trip_time,speed,num_of_taxis
0,4,1,0,0,0,0,0,0,0,0,...,13.3,16.0,0.0,0.06,0.0,0.0,2.543171,11.890650,12.167499,41
1,4,0,1,0,0,0,0,0,0,0,...,13.3,16.0,0.0,0.06,0.0,0.0,2.842436,14.737821,11.223936,78
2,4,0,0,1,0,0,0,0,0,0,...,13.3,16.0,0.0,0.06,0.0,0.0,2.235484,11.183333,11.346154,62
3,4,0,0,0,1,0,0,0,0,0,...,13.3,16.0,0.0,0.06,0.0,0.0,2.640308,11.701795,12.651760,65
4,4,0,0,0,0,1,0,0,0,0,...,13.3,16.0,0.0,0.06,0.0,0.0,2.635000,11.158889,13.186688,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519912,263,0,0,0,0,0,0,0,0,0,...,5.1,24.0,0.0,0.02,0.0,0.0,1.634367,8.410748,11.789618,245
519913,263,0,0,0,0,0,0,0,0,0,...,5.1,24.0,0.0,0.02,0.0,0.0,1.564640,8.290106,11.409292,347
519914,263,0,0,0,0,0,0,0,0,0,...,5.1,24.0,0.0,0.02,0.0,0.0,1.736828,8.729789,12.242927,268
519915,263,0,0,0,0,0,0,0,0,0,...,5.1,24.0,0.0,0.02,0.0,0.0,1.708687,7.692929,13.436525,198
519916,263,0,0,0,0,0,0,0,0,0,...,5.1,24.0,0.0,0.02,0.0,0.0,1.567273,6.515618,14.888343,143

In [9]:
main_df.shape

(519917, 45)

In [11]:
dataset = main_df.values

In [14]:
X = dataset[:,0:44]

In [15]:
X

array([[  4.        ,   1.        ,   0.        , ...,   2.54317073,
         11.89065041,  12.16749909],
       [  4.        ,   0.        ,   1.        , ...,   2.8424359 ,
         14.73782051,  11.22393627],
       [  4.        ,   0.        ,   0.        , ...,   2.23548387,
         11.18333333,  11.34615387],
       ...,
       [263.        ,   0.        ,   0.        , ...,   1.73682836,
          8.72978856,  12.24292714],
       [263.        ,   0.        ,   0.        , ...,   1.70868687,
          7.69292929,  13.43652456],
       [263.        ,   0.        ,   0.        , ...,   1.56727273,
          6.51561772,  14.88834273]])

In [16]:
Y = dataset[:,44]

In [17]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_val_and_test, Y_train, Y_val_and_test = train_test_split(X_scale, Y, test_size=0.3)
X_val, X_test, Y_val, Y_test = train_test_split(X_val_and_test, Y_val_and_test, test_size=0.5)

In [23]:
from keras.models import Sequential
from keras.layers import Dense

In [24]:
model = Sequential([
    Dense(32, activation='relu', input_shape=(10,)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid'),
])